### ISSUE TITLE
protein embedding is odd

### ISSUE THREAD

**Issue by jxzly** [songlab-cal/tape#101]
the dim=359 of output is so large, mean~7

**Comment by rmrao** [comment]
Sorry for taking so long to get to this. Not sure I understand the question though. Which dimension of the output is this? What are you taking a mean over?

**Comment by RegiusQuant** [comment]
For single protein sequence, the embedding is L*D
In dim 359 for D, the distribution of embedding is so large

**Comment by rmrao** [comment]
I'm having a hard time understanding what you're asking, or what the issue is. I suppose the 359th dimension has high mean? No idea why - training is a random process, and so may result in some odd results occasionally. Not sure the layer norms are optimally placed for this model.

If you have an actual question, let me know...
