### ISSUE TITLE
cpu-only environment

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [songlab-cal/tape#2]
Can I run it in a cpu-only environment?

**Comment by nickbhat** [comment]
Could you say more about what you are trying to run cpu-only? Pretraining, fine-tuning, embedding, etc.

**Comment by rmrao** [comment]
I actually had added support for this throughout, but there were a few bugs. Just fixed them in #3 so if you clone the repository, the commands (except for `tape-train-distributed`) can be run with the `--no_cuda` flag, which should work in a cpu-only environment.

It is much, much slower to do this than to run via gpu, obviously (60-100x slower for embedding). We're thinking of adding in some of the smaller unirep models (e.g. babbler-60) since a lot of people seem to like using those instead of the large ones, and those should be at least reasonably quick on cpu.

**Comment by Kevin-chen-sheng** [comment]
thanks @rmrao.
