### ISSUE TITLE
Language modeling targets

### ISSUE THREAD

**Issue by Kyonio** [songlab-cal/tape#32]
In the language modeling task, I think your goal is to predict the next amino acid? But when constructing the dataset, the targets look exactly the same with the original inputs (except for the padding constant value). If I did not misunderstand... Could you check that part?

**Comment by rmrao** [comment]
If you're looking at the LSTM model, they are the same, but the LSTM shifts / pads its input to get the appropriate result. It's easy enough to test this - if they're not shifted appropriately then training should give you zero loss very quickly.

If you're looking at the UniRep model, I think the basic scheme works but as with my comment in #33, I have not extensively debugged UniRep training so it is possible it is bugged.

**Comment by Kyonio** [comment]
Yes, I know that LSTM models require shifts. But when you register the "language modeling" task in [datasets.py](https://github.com/songlab-cal/tape/blob/2e5bfa2249274392baf045df7de1490e92d47ed1/tape/datasets.py#L354-L357). The inputs and targets share the same pad_sequence function.

I checked the pad_sequence function. it seemed that the processed inputs and the targets are exactly the same except for the paddings. However, the padding index '-1' will be ignored when doing prediction. So basically they will be the same? (And I am doing the LM experiments now, the loss doesn't vanish so far...)
Could you clarify that? Thx!

**Comment by rmrao** [comment]
So what I'm saying is that I make the processed inputs and targets the same from the dataset and then shift them inside the forward function of `modeling_lstm.py`. See [here](https://github.com/songlab-cal/tape/blob/2e5bfa2249274392baf045df7de1490e92d47ed1/tape/models/modeling_lstm.py#L189-L194).

This is largely because the LSTM is a *bidirectional* model, so if I shifted at input I would need to provide different shifted targets for the forward and reverse components of the LSTM. Of course, that is a reasonable alternative way of doing this, but the two are equivalent.
