### ISSUE TITLE
UniRep's representation

### ISSUE THREAD

**Issue by SorteKanin** [songlab-cal/tape#53]
I've looked at the UniRep implementation and I'm a bit confused about the representation that it uses to do, for example, stability predictions. It seems that it uses the last hidden state to do the prediction - but doesn't the UniRep paper suggest taking the mean of all the hidden states?

For reference, the stability task for UniRep:
```
@registry.register_task_model('fluorescence', 'unirep')
@registry.register_task_model('stability', 'unirep')
class UniRepForValuePrediction(UniRepAbstractModel):

    def __init__(self, config):
        super().__init__(config)

        self.unirep = UniRepModel(config)
        self.predict = ValuePredictionHead(config.hidden_size * 2)

        self.init_weights()

    def forward(self, input_ids, input_mask=None, targets=None):

        outputs = self.unirep(input_ids, input_mask=input_mask)

        sequence_output, pooled_output = outputs[:2]
        outputs = self.predict(pooled_output, targets) + outputs[2:]
        # (loss), prediction_scores, (hidden_states)
        return outputs
```
Notice that it uses the pooled output, which we can see comes from this model:
```
@registry.register_task_model('embed', 'unirep')
class UniRepModel(UniRepAbstractModel):

    def __init__(self, config: UniRepConfig):
        super().__init__(config)
        self.embed_matrix = nn.Embedding(config.vocab_size, config.input_size)
        self.encoder = mLSTM(config)
        self.output_hidden_states = config.output_hidden_states
        self.init_weights()

    def forward(self, input_ids, input_mask=None):
        if input_mask is None:
            input_mask = torch.ones_like(input_ids)

        # fp16 compatibility
        input_mask = input_mask.to(dtype=next(self.parameters()).dtype)
        embedding_output = self.embed_matrix(input_ids)

        encoder_outputs = self.encoder(embedding_output, mask=input_mask)
        sequence_output = encoder_outputs[0]
        hidden_states = encoder_outputs[1]
        pooled_outputs = torch.cat(hidden_states, 1)

        outputs = (sequence_output, pooled_outputs)
        return outputs
```
Where it seems that the pooled outputs is the concatenation of the last cell state and last hidden state.

Why does TAPE use this concatenated representation, when the UniRep paper uses a mean over all the hidden states as its representation?

**Comment by rmrao** [comment]
In the paper we used an attention-weighted mean over hidden states (which can be found in the [old repository](https://github.com/songlab-cal/tape-neurips2019)). I haven't made significant attempts to optimize the outputs of the UniRep model in pytorch, since it is mostly provided if people want to extract embeddings. In this case we provided an option to output all hidden states so that people can train whatever model they like on top of them.

I believe strictly speaking UniRep uses a concatenation of the mean over all hidden states in addition to the last hidden state. If you would like to submit a pull request to duplicate this behavior, I'd be happy to merge it.
