### ISSUE TITLE
cuda out of memory when increasing samplesize

### ISSUE THREAD

**Issue by kkpsiren** [songlab-cal/tape#80]
Hi guys, 
thanks for the clear instructions for downstream model training. I'm training a downstream task via the ```adding_task.py```and it works great when my data is 1000 samples. However when increasing the sample size to 100x, CUDA will go out of mem while keeping params the same. So maybe there's a memory buildup during the data loading? Could you point me to the right direction? Thanks

**Comment by rmrao** [comment]
I'm not sure what you mean. Are you increasing the batch size, or keeping the batch size fixed while increasing training set size?

**Comment by kkpsiren** [comment]
so batch size is constant, the only thing that is changing is the number of samples in the training dataset. Thanks for replying

**Comment by rmrao** [comment]
Huh... that's odd. I haven't seen this issue with TAPE before. Are all the samples the same size?

**Comment by kkpsiren** [comment]
thanks for replying, I think the issue is not length. So I trained a downstream model with a small subset, and when evaluating against a bigger dataset sorted by descending length I get memory errors after 175 batches if I use ```batch_size: 16``` whereas ```batch_size: 8``` gets me to 276 batches before memory error

**Comment by rmrao** [comment]
Update: TLDR I'm probably going to deprecate TAPE's training code and recommend people switch to a proper training framework.

So since the time TAPE was released, there have been a number of training frameworks released for pytorch. I have switched to using pytorch lightning and fairseq, depending on the project. DeepSpeed is also a good choice. It is difficult to maintain the framework for TAPE's training that was written before these frameworks were released, especially with continual updates to hardware and changes to the way pytorch distributed works. So I'd recommend trying to use one of these frameworks.

If you're specifically just trying to train transformer models, I'd strongly recommend either fairseq or DeepSpeed, which have excellent implementations for very fast multi-GPU training.
